dataset_conf:
    filter_conf:
        max_length: 2048
        min_length: 0
    resample_conf:
        resample_rate: 16000
    speed_perturb: false
    reverb_prob: 0.2
    noise_prob: 0.4
    feats_type: 'fbank'
    fbank_conf:
        num_mel_bins: 80
        frame_shift: 10
        frame_length: 25
        dither: 1.0
    spec_aug: true
    spec_aug_conf:
        num_t_mask: 1
        num_f_mask: 1
        max_t: 20
        max_f: 40
    shuffle: true
    shuffle_conf:
        shuffle_size: 1500
    sort: false
    batch_conf:
        batch_size: 256

model:
    hidden_dim: 32
    preprocessing:
        type: linear
    backbone:
        type: mdtc
        num_stack: 3
        stack_size: 3
        kernel_size: 5
        hidden_dim: 32
        causal: True

optim: adam
optim_conf:
    lr: 0.001
    weight_decay: 0.00005

training_config:
    grad_clip: 5
    max_epoch: 20
    log_interval: 10
    criterion: max_pooling